#ifndef CONSTS_H
#define CONSTS_H

#define MAX_DATA_SIZE 256
#define MAX_NODE_NAME_SIZE 32
#define FIFO_FILE "/tmp/myfifo"
#define FIFO_FILE_PERMISSIONS 0666

#define SELECT_TIMEOUT_S 5

#define JOIN_MAGIC 0xAAAABBBB
#define MAX_PENDING_JOINS 32

#define JOIN_ACCEPT_TIMEOUT_S 1
#define JOIN_ACCEPT_RETRIES 5

#define JOIN_REQUEST_TIMEOUT_S 1
#define JOIN_REQUEST_RETRIES 20


#define JOIN_PENDING_TTL_S 20

#define MAX_UNICAST_PAYLOAD 512
#endif
