#ifndef CONSTS_H
#define CONSTS_H

#define MAX_DATA_SIZE 256
#define MAX_NODE_NAME_SIZE 32
#define FIFO_FILE "/tmp/myfifo"
#define FIFO_FILE_PERMISSIONS 0666

#define SELECT_TIMEOUT_S 5

#define JOIN_MAGIC 0xAAAABBBB
#define MAX_PENDING_JOINS 32

#define JOIN_ACCEPT_TIMEOUT_S 1
#define JOIN_ACCEPT_RETRIES 30

#define JOIN_REQUEST_TIMEOUT_S 10
#define JOIN_REQUEST_RETRIES (1 << 16)

#define JOIN_ACK_RESEND_S 1
#define JOIN_ACK_MAX_RETRIES 30
#define JOIN_ACK_ACK_SEND_COUNT 10


#define JOIN_PENDING_TTL_S 200

#define MAX_UNICAST_PAYLOAD 512
#endif
